# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 230, 372, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.meterToFeetRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.meterToFeetRadio.setObjectName("meterToFeetRadio")
        self.gridLayout.addWidget(self.meterToFeetRadio, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.feetToMeterRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.feetToMeterRadio.setChecked(True)
        self.feetToMeterRadio.setObjectName("feetToMeterRadio")
        self.gridLayout.addWidget(self.feetToMeterRadio, 0, 0, 1, 1)
        self.inputField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inputField.setObjectName("inputField")
        self.gridLayout.addWidget(self.inputField, 1, 2, 1, 1)
        self.resultLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.resultLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultLabel.setObjectName("resultLabel")
        self.gridLayout.addWidget(self.resultLabel, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(200, 340, 122, 27))
        self.convertButton.setObjectName("convertButton")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(450, 340, 123, 27))
        self.quitButton.setObjectName("quitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.meterToFeetRadio.setText(_translate("MainWindow", "Meters to Feet"))
        self.label_2.setText(_translate("MainWindow", "is equivalent to"))
        self.label_3.setText(_translate("MainWindow", "Meters"))
        self.feetToMeterRadio.setText(_translate("MainWindow", "Feet to Meters"))
        self.inputField.setText(_translate("MainWindow", "0"))
        self.resultLabel.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Feet"))
        self.convertButton.setText(_translate("MainWindow", "CONVERT"))
        self.quitButton.setText(_translate("MainWindow", "QUIT"))
